In [1]:
import numpy as np

Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
n = np.arange(10)[::-1]
n

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [3]:
n = -np.sort(-np.arange(10))
n

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [7]:
diag_matrix = np.diag(n)
diag_matrix

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [16]:
sum(diag_matrix[i][i] for i in range(len(diag_matrix)))
    

45

In [15]:
sum_diag = 0
for i in range(len(diag_matrix)):
    sum_diag += diag_matrix[i][i]
sum_diag

45

Задание 3
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [19]:
import pandas as pd

In [20]:
ratings = pd.read_csv('ratings.csv')

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [70]:
r = ratings[ratings["rating"]==5.0].groupby(["movieId", "rating"]).count().sort_values("userId", ascending=False).head(1).reset_index()

In [72]:
r['movieId']

0    318
Name: movieId, dtype: int64

In [45]:
ratings_5_count = ratings[ratings["rating"]==5.0]["movieId"].value_counts()

In [47]:
ratings_5_count.idxmax()

318

Задание 4
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [74]:
power = pd.read_csv('power.csv')
power.head()

country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [78]:
power[ power['country'].str.contains('lat', case=False) ]['country'].unique()

array(['Latvia'], dtype=object)

In [89]:
baltics = ['Lithuania' , 'Estonia', 'Latvia']
categories = [4,12,21]
years = [2005, 2006, 2007, 2008, 2009, 2010]
power[power.country.isin(baltics) & power.category.isin(categories) & power.year.isin(years) & power['quantity']>0]['quantity'].sum()

240481.0

Задание 5
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [17]:
from numpy import linalg
eq_sys = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
eq_res = np.array( [4, 12, -3] )
linalg.solve(eq_sys, eq_res)

array([ 0.46666667,  3.84444444, -5.55555556])

In [18]:
np.allclose( np.dot(eq_sys, linalg.solve(eq_sys, eq_res)), eq_res )

True